from random import randint

arquivo = open('exemploPesquis.txt','w',encoding= 'UTF-8')
for i in range(0,100):
  arquivo.write('T')
  arquivo.write(str(randint(0,500)))
  arquivo.write(';')
  arquivo.write(str(randint(1000000,5000000)))
  arquivo.write(';')
  arquivo.write(str(randint(10000000,50000000)))
  arquivo.write(';')
  arquivo.write(str(randint(0,6)))
  arquivo.write(';')
  arquivo.write(str(randint(11,65)))
  arquivo.write(';')
  arquivo.write(str(randint(0,10)))
  arquivo.write(';')
  arquivo.write(str(randint(0,20)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write(';')
  arquivo.write(str(randint(0,10)))
  arquivo.write(';')
  arquivo.write(str(randint(0,20)))
  arquivo.write(';')
  arquivo.write(str(randint(0,10)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write(';')
  arquivo.write(str(randint(0,99)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write(';')
  arquivo.write(str(randint(0,2)))
  arquivo.write(';')
  arquivo.write(str(randint(0,12)))
  arquivo.write(';')
  arquivo.write(str(randint(1900,2019)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write(';')
  arquivo.write(str(randint(0,2)))
  arquivo.write(';')
  arquivo.write(str(randint(0,5)))
  arquivo.write('\n')
